### ISSUE TITLE
Featuer request: Grab user albums from Tidal

### ISSUE THREAD

**Issue by ScrewTSW** [jonaski/strawberry#139] opened 2019-04-25 12:55 UTC
Make it possible to play user's own albums instead of being forced to search for songs manually every time.

Would be really nice to be able to just add an entire user album to the current playlist.

**Comment by jonaski** [comment] 2019-04-25 15:12
Duplicate of https://github.com/jonaski/strawberry/issues/25

**Closed by jonaski** 2019-04-25 15:12 UTC
