### ISSUE TITLE
Create new version of strawberry

### ISSUE THREAD

**Issue by gianlucapettinello** [jonaski/strawberry#205] opened 2019-07-06 05:18 UTC
Many improvements don so far. Do you think it is possible to create a new version?
Thanks
Gianluca

**Comment by alekksander** [comment] 2019-07-06 12:53
if i may – what is Your suggestion actually about? new numeration? new visual design?

**Comment by gianlucapettinello** [comment] 2019-07-06 15:12
No simply create version 0.5.6

**Comment by gianlucapettinello** [comment] 2019-07-06 15:13
So the nice improvements can trickle in arch withou installing git version from AUR :)

**Comment by ArielRosenfeld** [comment] 2019-07-07 17:04
the playback stopping fix would be a nice fix (bug #106)

**Comment by jonaski** [comment] 2019-07-14 20:33
There are a lot of critical changes done like the schema updates so I don't want to rush it before we get everything properly tested. Also, 0.5.5 is very stable with few bugs. I'll probably make a new release within a few weeks.
But if someone can volunteer to do testing it would be nice. I can make a list of specific things that needs testing.

**Comment by gianlucapettinello** [comment] 2019-07-14 21:05
Ok, thanks, I will wait

**Comment by gianlucapettinello** [comment] 2019-07-14 21:06
And if there is something to test please let me know

**Comment by jonaski** [comment] 2019-07-24 17:54
This took a while longer since I found some more bugs.
I have solved some memory leaks, some in database.cpp (all previous versions affected too) and some in internet services caused by NewClosure (0.5.5 not affected).
There are a few minor bugs remaining still, and then I will make a list of what needs to be tested.
The biggest issue right now is probably the analyzer https://github.com/jonaski/strawberry/issues/155 - But I'm not counting on fixing that before the next release.
https://github.com/jonaski/strawberry/issues/213 should be fixed before next release.

**Comment by gianlucapettinello** [comment] 2019-07-24 17:57
Ok, I'll try to look at it and help as I can

**Comment by jonaski** [comment] 2019-07-28 09:31
Here is a list of what to test:

Before you start make a backup your current configuration and db file:
Backup the ~/.config/strawberry and ~/.local/share/strawberry and remove them.
The important files are ~/.config/strawberry/strawberry.conf, ~/.local/share/strawberry/strawberry.db and ~/.local/share/strawberry/strawberry/albumcovers.
Make a backup of ~/.local/share/strawberry/strawberry/albumcovers/ and remove the directory too.

Create a folder with some albums without album covers. Make sure the albums are in separate directories.
Make sure at least one album is with the album cover image in the directory, one has embedded album cover, and some without album covers at all.

Start with version 0.5.5:
Add a music directory to the collection through the settings.
Use the cover manager to scan for remaining album covers so that they have automatic cover (in albumcovers dir), add some files to the playlist too.

Upgrade to the latest code from git, start on the terminal and watch for any errors. It should upgrade the schemas automatically.
See that everything is like before in the collection, playlists and album covers are loaded correctly.
You can see where album covers come from in summary on the edit tag dialog.

**1. Test the collection and album cover manager**

a) Add music to the playlist and test to play an album, the cover should be automatically downloaded. Check and see that the album cover is updated in the collection.
b) Go to the cover manager and fetch all albums, see that it gets the best album covers from each provider and that the collection is updated with the new covers.
c) Go the the cover manager, right click on the album and search for album covers, select another album cover and make sure it gets updated both in the collection, and when playing a song.

Exit and delete all the configuration, strawberry.conf, strawberry.db and the albumcovers directory.
Add a music directory to the collection and make sure all albums are loaded fine.

Redo everything in the list above.

**2. Test editing tags **

a) Check the summary in the edit tags dialog, try setting a new album cover.

b) Edit tags with edit track information in the playlist or in the collection
   Try editing a single song, an entire albums, and different tags.
   Assume there are no crashes, and that it doesn't get stuck.
c) Use the automatic tag fetcher and see that it works. (its a bit slower now because it delays the connections not too exceed the requests limitations).

**3. Test lyrics **

a) Check that lyrics are received for songs in the context (right click and enable).
   Run from the terminal to see that there is a no match if no lyrics are shown.
   Specfically issue: https://github.com/jonaski/strawberry/issues/188
   If there are no problems, I will close the issue since I can't reproduce any problems on any system.


** 4. Test Tidal and Qobuz **

You can start a free trial, you need to enter your credit card, but you can cancel the subscription afterwards and you will get one month free.
Tidal: https://tidal.com/masters
Qobuz: https://www.qobuz.com/us-en/music/streaming/offers

For Qobuz you need an app id and secret in the settings, you can Google to find one.

a) Test searching for songs and playing them.
b) Test adding different favorites (artists, albums and songs).

** 5. Test Subsonic **

a) Test Subsonic with different servers, like Airsonic and Ampache.

** 6 Test device support **

Test loading songs, copying and deleting songs.

a) Test a mass storage device
b) Test a MTP device
c) test an iPod

You can also look at the Changelog, and test whatever else is changed since last version:
https://github.com/jonaski/strawberry/blob/master/Changelog

**Comment by jonaski** [comment] 2019-08-02 22:11
I found some bugs while testing. Turns out since introducing the live scanning, new subdirs never got added to the watcher, so the watcher was partially broken. Fixed now: https://github.com/jonaski/strawberry/commit/7b13c0d05969a273d8211b94c99c67036ab0b7fa
Old remembered devices could not be read, and caused assertion when trying to drop them since the FTS5 change, fixed now: https://github.com/jonaski/strawberry/commit/2d3f41da6f08e001f70cfeb2c172693c1e51eedf

**Closed** 2019-08-03 12:12 UTC
