### ISSUE TITLE
strawberry does not work well with Media Player applet of KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#90] opened 2019-03-06 14:12 UTC
Hi

KDE Plasma has an applet called Media Player, you can enabled it in system tray settings.
This applet can play/pause, play next/previous track and control the volume level with the mouse wheel.
Volume control is not working as expected when I play music with strawberry: strawberry icon is missing in the OSD shown by KDE Plasma (see the screenshot) and there is a delay to change the voume level.
I scroll up/down while hover over the icon of  the applet in the systray and the volume level does not change immediately. There is some seconds of delay.
These problems (missing icon in the OSD and delay) do not occur when I use Clementine, for example.

My system:
Arch Linux
KDE Plasma 5..12.2 desktop environment
strawberry 0.5.2 from Arch repos

![mediaplayer applet](https://user-images.githubusercontent.com/15967631/53887053-35e6b300-4000-11e9-8c0e-30efac3518e4.png)

**Comment by dandydon414** [comment] 2019-03-08 17:45
I'm running plasma 5.15.12 and I don't have this problem, try the Audio volume (win7 mixer) widget.

**Comment by glaubersm** [comment] 2019-03-08 18:55
The problem is between strawberry and media player applet.
Media player applet is the icon that appears in systray on the left side of the lock icon in my screenshot.
Sound applet of Plasma works fine.

**Comment by dandydon414** [comment] 2019-03-08 21:03
okay gotcha.. I really don't use the media player applet. I much prefer the win7 mixer widget and the media controls work fine.
![Screenshot_20190308_160149](https://user-images.githubusercontent.com/48139014/54055636-ad147680-41bb-11e9-85ff-e335be64f52b.png)

**Comment by alekksander** [comment] 2019-03-09 00:10
cannot confirm, but i don't have PA installed on my system. could that be the case? 

![image](https://user-images.githubusercontent.com/3148302/54062703-0e623700-4208-11e9-9118-512ff42cd510.png)

**Comment by glaubersm** [comment] 2019-03-09 01:18
Weird. I just installed strawberry-git on Arch linux and the bug persists.
I also have strawberry installed on neon dev unstable via deb package and the same bug occurs.

**Comment by alekksander** [comment] 2019-03-09 08:11
Sorry if it's far unwise suggestion, but could You remove pulse audio? Do You have nvidia graphica? I've seen weirdest ui bugs imaginable with nVidia cards. Also are You unser wayland? If so, try ~~good~~ Old X's.

**Comment by glaubersm** [comment] 2019-03-09 16:04
pulse audio works fine on my systems.
I use intel hd graphics and intel hd 4000.
The bug occurs on both Wayland and X11 sessions.

I have several players installed on Arch Linux.
Weirdly the bug only occurs with strawberry.

**Comment by jonaski** [comment] 2019-03-11 22:24
I will do some testing on this when I get some time, I don't use KDE myself so I have to boot up a machine with KDE.
But I think the reason it works in Clementine is because it's still using Qt 4, unless you compiled the Qt 5 version. I suspect it might be a bug in KDE that only affects Qt 5 applications.

**Comment by glaubersm** [comment] 2019-03-11 22:33
I have the following Qt5 players installed here:

qmmp
yarock
smplayer
vlc
qoob

All of them work fine with the media player applet.

**Comment by jonaski** [comment] 2019-03-11 22:36
I see. Will look into it.

**Comment by jonaski** [comment] 2019-03-12 23:49
I've done some changes to the mpris code that might have solved this.
Can you try a development build 0.5.2-67 or later and see if it fixes it.
https://builds.strawbs.net/

**Comment by glaubersm** [comment] 2019-03-13 01:35
Installed strawberry_0.5.2-69-g4148c28_amd64.deb on Neon dev unstable.
Bug persists.

**Comment by NucleaPeon** [comment] 2019-03-19 21:16
QT 5.11.3, plasma 5.14.5.1 on Gentoo (installed from git, Version 0.5.1-29-g3241815), I do not see this bug. I'll also try upgrading my version of strawberry.

I can try installing it on an arch laptop to verify, but it _could be_ an Arch bug; I've had middling results with system stability when I've used arch over the years.

![Screenshot_20190319_141200](https://user-images.githubusercontent.com/1475151/54642262-69d6c500-4a51-11e9-9bd7-629c4c34ee5b.png)

**Comment by alekksander** [comment] 2019-03-19 23:02
wheel up/down on that applet icon in tray → the volume notification in the middle of Your screen (assuming You didn't modify it with own/folks at reddit code) is where You should look at.

![BGS](https://user-images.githubusercontent.com/3148302/54647611-6ec46480-4aa3-11e9-90a2-3f44812b20f1.png)

**Comment by glaubersm** [comment] 2019-03-19 23:52
Weird...
I just installed srawberry-git-full on Arch Linux and the bug persists.
Same thing on Neon dev unstable running strawberry_0.5.2-69-g4148c28_amd64.deb .

**Comment by NucleaPeon** [comment] 2019-03-20 20:10
@alekksander I might have made some progress on your issue. (Sorry, I didn't quite register that the issue was a scroll wheel problem)

When I initially installed strawberry from the 0.48 source, the .desktop file was missing the strawberry icon. I manually added it in through the KMenu Edit Applications... window. Since then, I've upgraded strawberry twice and the icon has remained in place.

I decided to comment out the Icon line in the .desktop file to see if I could reproduce the issue, and yes. If I remove the icon line, mouse-wheeling over the media player tray icon shows no strawberry.

![Screenshot_20190320_130747](https://user-images.githubusercontent.com/1475151/54715674-352a4280-4b11-11e9-8a69-fb2b1cf4f9f2.png)

My .desktop file is at `/usr/local/share/applications/strawberry.desktop` and is this:


    [Desktop Entry]
    Version=1.0
    Type=Application
    Name=Strawberry
    GenericName=Strawberry Music Player
    Comment=Plays music
    Exec=strawberry %U
    TryExec=strawberry
    # Icon=strawberry
    Terminal=false
    Categories=AudioVideo;Player;Qt;Audio;
    StartupNotify=false
    MimeType=x-content/audio-player;application/ogg;application/x-ogg;application/x-ogm-audio;audio/flac;audio/aac;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/vorbis;audio/vnd.rn-realaudio;audio/x-wav;audio/x-flac;audio/x-oggflac;audio/x-vorbis;audio/x-vorbis+ogg;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-ms-wma;audio/x-musepack;audio/x-pn-realaudio;audio/x-scpls;audio/x-speex;video/x-ms-asf;

**Comment by jonaski** [comment] 2019-04-19 08:36
I've installed arch on a physical machine, I can't reproduce the problems with the delay changing volume. However I see that the icon was missing when changing volume, it should be fixed now.
https://github.com/jonaski/strawberry/commit/844c4a28f4b1f907990625425a4ce01005df39aa

**Closed** 2019-04-19 08:56 UTC
Labels: bug, confirmed

**Comment by glaubersm** [comment] 2019-04-19 16:35
I'm using strawberry-full-git on Arch Linux and I can confirm that this bug is fixed.
Thank you all.
