### ISSUE TITLE
[FEATURE REQUEST] Add context menu for tidal songs to download the file for local storage

### ISSUE THREAD

**Issue by ScrewTSW** [jonaski/strawberry#190] opened 2019-06-25 13:50 UTC
Since the audio is already being losslessly streamed over the internet, it should be easy to use gstreamer to save it or potentially transcode it through ffmpeg.

We could even get a dialog that would allow us to tweak the ffmpeg parameters like encoder, output format, bitrate, etc.

**Comment by jonaski** [comment] 2019-06-25 16:57
I dont know the legal consequences of allowing downloads. We are not a partner and have not signed any agreement.
Duplicate of https://github.com/jonaski/strawberry/issues/176

**Closed by jonaski** 2019-06-25 16:57 UTC
