### ISSUE TITLE
Show user's favorite items in Tidal

### ISSUE THREAD

**Issue by tcpj** [jonaski/strawberry#25] opened 2018-11-02 15:33 UTC
Would be nice to have support for browsing thru my favorites on Tidal, incl. playlists, albums, artists. There is currently no way to save favorite albums in strawbs

**Comment by mroova** [comment] 2018-11-04 17:07
I agree - that would be a great feature :)
I'm not a programmer but maybe the code of the linked plugin could be of some help:
https://github.com/arnesongit/plugin.audio.tidal2
All the best.

**Comment by jonaski** [comment] 2018-11-04 19:59
The plan is to have tabs on top of what is now the internetsearchview (used for both Tidal and Deezer) where you can select either search, playlists and favorites as tabs. I do not really want it the way it is in Clementine.

**Comment by mroova** [comment] 2018-11-04 20:57
The plan sounds really good - that would be very convenient.

**Comment by ScrewTSW** [comment] 2019-04-29 08:18
bump.

Hello, What are your plans with this issue.
Do you think you would be able to work on it, or would you welcome some help? (would have to dust off my C++ though :D )

**Comment by jonaski** [comment] 2019-05-05 17:48
I'm unsure whether Tidal have closed down the API method we use, see https://github.com/jonaski/strawberry/issues/148
Can you still login?

**Comment by jonaski** [comment] 2019-05-06 16:44
I fixed the login problems, basically just switched API URL to a new one.
@ScrewTSW I plan to do the Tidal, but I got too busy with fixing other things, and it's not like I'm in a hurry adding this. If you can do it faster than me it would be nice.
I was unsure whether to use a backend or not, if we use a backend we can just use the same model like the collection with a separate song table and write it's own view with that.
The other option is to not use a backend and just fetch the albums each time, then we could create a model and view similar to the ones used for the search.

**Comment by jonaski** [comment] 2019-05-06 16:47
I planned to use a tab widget to switch between search and favorites.

**Comment by ScrewTSW** [comment] 2019-05-07 09:56
> I fixed the login problems, basically just switched API URL to a new one.
> @ScrewTSW I plan to do the Tidal, but I got too busy with fixing other things, and it's not like I'm in a hurry adding this. If you can do it faster than me it would be nice.
> I was unsure whether to use a backend or not, if we use a backend we can just use the same model like the collection with a separate song table and write it's own view with that.
> The other option is to not use a backend and just fetch the albums each time, then we could create a model and view similar to the ones used for the search.

It would also be helpful if you could share some approximate timeframe. I would hate to delay the development if you plan on working on it in the near future.

**Comment by jonaski** [comment] 2019-05-19 13:12
I'm working on this now, but it took longer than I expected. I've implemented it with 3 backends, for artists, albums and songs (favorites in Tidal). This means that it has it's own songs table for each 3 and you don't need to reload it from Tidal each time you start, only if you want to update them.
I also had to split the Tidal API service into different classes and subclasses, so it uses the same functions as for search without duplicating the code.

Here is how it looks so far:

![image](https://user-images.githubusercontent.com/10343810/57982616-f0a32080-7a47-11e9-8397-01effe8978d8.png)

**Comment by jonaski** [comment] 2019-05-27 20:00
I've added support for favorite artists, albums and songs now. https://github.com/jonaski/strawberry/commit/890fba0f61cb0c32a3abecd533c15e740bfe88b9
Playlists remaining.
It would also be nice to be able to directly add songs/albums/artists to favorites from the search view, but I could not find the API request to do that.
It would be nice if someone can test and report back any problems.

**Comment by tcpj** [comment] 2019-05-28 11:00
I just pulled the request straight outta Tidal:
```POST v1/users/43632093/favorites/tracks?countryCode=CZ```
Form data:
```
trackIds: 47224829
```
```POST v1/users/43632093/favorites/albums?countryCode=CZ```
Form data:
```
albumIds: 99625714
```

**Comment by tcpj** [comment] 2019-05-28 11:01
And to remove from favorites:
```DELETE v1/users/43632093/favorites/albums/99625714?countryCode=CZ```

**Comment by tcpj** [comment] 2019-05-28 11:22
So I am testing the tabs but I have problem with loading all of my music. Only few albums are shown in the tab. Same with artists.

**Comment by jonaski** [comment] 2019-05-28 15:37
My fault. There was a sonity check used by the search limit, i've removed it now.
This fixes the albums listing limit, but artists are still limited to 10 because it does not offset artists yet, I will fix that too.
https://github.com/jonaski/strawberry/commit/20f9108ebfff8fc72d4a4c842cf40248cca42d5c

**Comment by jonaski** [comment] 2019-05-30 17:00
I'ts betting better now. Here is what's new in the last couple of days:
* Added offset to all requests
* All requests are now queued so it does not flood the severs
* The database songs tables are updated to support artist_id, album_id and song_id that can be used to add/remove items from the favorites, etc
* The collection model is updated distinguish albums by album_id so multiple albums by the same name aren't shown as the same.
* Added button to abort (the songs will not be deleted or updated), if there is an error there will be a close button shown instead
* Fixed plenty of bugs caused by the recent changes I did to Tidal

**Comment by jonaski** [comment] 2019-06-07 18:25
Added the ability to add favorites from the search view, and the ability to remove favorites from artists/albums/songs
https://github.com/jonaski/strawberry/commit/5c2ca1e3d9dee9c7ae5c02460924499fe2eed101

**Comment by jonaski** [comment] 2019-06-09 01:13
@tcpj I have managed to authenticate to Tidal using OAuth token method, the only thing missing then is user id and country code which isn't received in the same way as the old login method, do you know how to receive it?

**Comment by tcpj** [comment] 2019-06-09 16:26
Sorry, no can do but I will take a look. I haven't know that you can oauth login til' now.

**Comment by jonaski** [comment] 2019-06-09 16:59
I figured it out, but when using oauth the streams are encrypted so the only thing remaining is to figure out if it's possible to pass the encryption key to gstreamer.

**Comment by jonaski** [comment] 2019-06-17 11:02
Tidal is closing down the login method we use so we need to switch to oauth. I've implemented oauth login but when using oauth the streams are encrypted. If we don't get an official developer account with Tidal then I'm afraid Tidal support will be gone sooner or later when the android method stops working, so I won't bother with the playlists integration.

**Closed by jonaski** 2019-06-17 11:02 UTC
Labels: enhancement

**Comment by ClaraCrazy** [comment] 2023-03-22 04:51
Sorry for bumping such an old issue. But has *anything* changed over the past four years? I'd absolutely love to see Playlist support for Tidal. I'm a Linux User, so strawberry is the only real option of properly enjoying tidal tracks, and not having playlists really is the only downside for me. 

I havent looked into the code, the Tidal API or anything, but if thats something that could be worked on, I wouldnt mind sending a few bucks for some coffee thats required while writing this :smile: 

Either way tho, appreciate the awesome player! Keep it up :heart:

**Comment by ClaraCrazy** [comment] 2023-04-02 07:56
I present to you: A playlist solution

https://github.com/ClaraCrazy/Tidal2Strawberry

Also working on a proper patch for favorites and playlists in strawberry since OG author seems to be dead
