### ISSUE TITLE
TIDAL lossless 

### ISSUE THREAD

**Issue by hvrba** [jonaski/strawberry#241] opened 2019-08-16 09:15 UTC
Excellent player, but unfortunately the lossless and high quality TIDAL stream don't work for me. (I have TIDAL HI-FI subscription and play master, lossless quality on other platforms without a problem)   

**System Information:**
 - Operating system: Linux Arch
 - Strawberry Version: 0.6.3

When I select lossless or hi-resolution in the tidal settings and try to play any track this error pops up:
**Could not determine type of stream.** when I change/downgrade the setting just to quality "high" it changes in the playlist from a file type "stream" to MP4 AAC and plays-streams without a problem.

How to get the lossless stream quality?
Thanks in advance.

**Comment by jonaski** [comment] 2019-08-16 17:51
I don't have a subscription now so I can't test but it worked fine a couple of months ago.
Maybe they switched to MQA? If so there isn't any decoder for that since it's a proprietary closed format

**Comment by hvrba** [comment] 2019-08-16 19:06
Hi. Thanks for your reply but It shouldn't be because of MQA, mqa is there for ages and due my knowledge it is activated only when compatible dac is supporting it and it is on masters /24 bit track the majority of tracks are lossless /16bit tracks. I tried different tracks. Tidal integration on PLEX -linux works fantastic, lossless quality works - 16bit/44khz.

**Comment by jonaski** [comment] 2019-08-16 21:06
If you can borrow me your login I can look into it

**Comment by pfelipm** [comment] 2019-08-25 19:11
I've just tried Tidal / Lossless and it is working as expected over here (versión 0.5.5-9-g69eeb4b).

**Comment by jonaski** [comment] 2019-08-25 23:27
Thanks for confirming but you should upgrade to 0.6.3

**Comment by jonaski** [comment] 2019-08-25 23:32
It is possible that newly created logins are broken, but old ones work, see: https://github.com/MusicPlayerDaemon/MPD/issues/545

**Comment by pfelipm** [comment] 2019-08-26 14:00
I already did, also working OK in 0.6.3... although not really sure about hires (master) tracks playing in 96/24.

**Comment by joaoraf** [comment] 2019-09-06 18:40
Hi, I am also having the same issue using Tidal with LossLess or HighRes. I am using strawberry compiled from GitHub (ad5e04bbcc14d9bffc944609deaf721238156930)

**Comment by jonaski** [comment] 2019-09-06 19:07
I got an offer for a new free trial so I renewed my subscription, I can confirm FLAC (Lossless) setting works fine for me.
So it's either related to your account (region or time it was registered) or the specific songs.

**Comment by jonaski** [comment] 2019-09-06 19:16
Does your account look like mine here, do you have HIFI or HiFi master?
![image](https://user-images.githubusercontent.com/10343810/64454513-74624500-d0eb-11e9-800c-0639df979a5d.png)

**Comment by NielsMayer** [comment] 2019-09-20 17:41
Tidal in Strawberry, unlike the Tidal2 plugin in Kodi ( https://github.com/arnesongit/plugin.audio.tidal2 ), does not deliver Hi Definition music. 

For example, this is what is output from Kodi playing an "MQA" album: (1293kbit/s, 48khz):

![](mtp:/V20/Internal%20storage/Capture+/Capture+_2019-09-20-10-33-18.png)

The same track/album played back in Strawberry -- 489kbps, 44,1khz

![image](https://user-images.githubusercontent.com/6306083/65347030-f134fa80-db92-11e9-9593-bc71dfb0aea9.png)

**Comment by jonaski** [comment] 2019-09-20 21:30
As for as I know there isn't any free and open source decoder for MQA. Kodi probably links to proprietary libraries.
But that wasn't really the issue here either.

Closing this as it works fine for me and @pfelipm and no one has shared their login.

**Closed by jonaski** 2019-09-20 21:30 UTC

**Comment by jonaski** [comment] 2019-09-22 22:48
I see that it's still not perfect, looks doing the preloading a bit sooner will fix it.

**Comment by jonaski** [comment] 2019-09-22 23:09
I increased the preload gap a bit, it's perfect now

**Comment by lkthomas** [comment] 2021-01-12 01:31
I can share an account that will be expired within 1-2 weeks if it helps. @jonaski I sent you an email to jonas@jkvinge.net, please check.

Also, I dig a bit deeper into the plugin.audio.tidal2 for Kodi, it's pure Python, on file resources/lib/koditidal.py
`
        self.quality = [Quality.lossless, Quality.high, Quality.low][min(2, int('0' + addon.getSetting('quality')))]
        self.use_rtmp = True if addon.getSetting('music_option') == '3' and self.quality <> Quality.lossless else False
        self.codec = ['FLAC', 'AAC', 'AAC'][min([2, int('0' + addon.getSetting('quality'))])]
        if addon.getSetting('music_option') == '1' and self.quality == Quality.lossless:
            self.codec = 'ALAC'
        elif addon.getSetting('music_option') == '2' and self.quality == Quality.lossless:                                                                                                                                                   
            self.codec = 'MQA'
`

and here,
`
    features = {
        # token: Login-Token to get a Session-ID
        # codecs: Supported Audio Codecs without encryption
        # rtmp: Uses RTMP Protocol for HIGH/LOW Quality Audio Streams
        # videosInPlaylists: True: numberOfVideos in Playlists is correct, False: returns 'numberOfVideos = 0' in Playlists
        # user-agent: Special User-Agent in HTTP-Request-Header
        'browser':   { 'token': browser,   'codecs': ['AAC'],                'rtmp': True,  'videoMode': 'HLS', 'videosInPlaylists': True,  'user-agent': None },
        'android':   { 'token': android,   'codecs': ['AAC', 'FLAC'],        'rtmp': False, 'videoMode': 'HTTP','videosInPlaylists': True,  'user-agent': 'TIDAL_ANDROID/686 okhttp/3.3.1' },
`

Does it meaning even using Android, it's still using FLAC to provide 24-bit streaming? I am not a programmer, I could only guess from the code but this should be able to get things started.

**Comment by jonaski** [comment] 2021-01-12 01:37
I got a subscription now, but thanks for the offer.
Streaming 44.1/16 and 48/24 FLAC works.

**Comment by jonaski** [comment] 2021-01-12 01:46
I think 48/24 FLAC only works with OAuth.

**Comment by lkthomas** [comment] 2021-01-12 02:07
> I think 48/24 FLAC only works with OAuth.

I feel like this is a minor change on the code itself, correct?

Can you please reopen this ticket?

**Comment by lkthomas** [comment] 2021-01-12 02:08
> I think 48/24 FLAC only works with OAuth.

OAuth isn't too complicated, I got my Token from Android Tidal official apps

**Comment by jonaski** [comment] 2021-01-12 02:12
Not sure what you mean, we already got OAuth working, you can play FLAC if the songs are available in FLAC, have the required subscription from TIdal, and the quality setting is set correctly in the settings.
Why should we open the issue, what is the problem?

**Comment by lkthomas** [comment] 2021-01-12 02:15
> Not sure what you mean, we already got OAuth working, you can play FLAC if the songs are available in FLAC, have the required subscription from TIdal, and the quality setting is set correctly in the settings.
> Why should we open the issue, what is the problem?

If so, are you being able to stream 24-Bit quality?

**Comment by jonaski** [comment] 2021-01-12 02:19
For some songs, yes. For example: Pink Floyd - Endless River.

**Comment by lkthomas** [comment] 2021-01-12 02:28
Not working for me,
![image](https://user-images.githubusercontent.com/581053/104261585-d3468400-54c0-11eb-81df-21de15522aeb.png)

Tried Audio quality setting to "Lossless" and "Hi-Resolution", same result.

**Comment by jonaski** [comment] 2021-01-12 20:53
But are you using OAuth?
What setting do you have for "Stream URL method"?

Strawberry is just requesting the URL with the quality parameter set to HI_RES, which is Hi resolution in the setting.
This is described here: https://github.com/openTIDAL/docTIDAL/wiki/track-streamUrl

**Comment by pfelipm** [comment] 2021-01-12 21:01
48/24 streams in Tidal do work for me 👇

![](https://user-images.githubusercontent.com/12829262/104374086-a1b1d500-5521-11eb-896e-b6d3f62dd41d.png)

**Comment by lkthomas** [comment] 2021-01-13 00:33
@jonaski  yes I am using OAuth, and running Hi Res, still not getting that 24 bit rate

**Comment by pnomolos** [comment] 2021-01-26 23:49
I pulled the Client ID from the OS X application and can confirm that only "High" and "Low" playback types work - on a track I've confirmed as having "Master" quality in the official application.  I tried all three "Stream URL method" options and none of them work for higher quality methods.

**Comment by pythonInRelay** [comment] 2021-11-09 13:28
This seems completely broken.

Account Created October 2021
Using oAuth key from Windows Desktop using Fiddler4

```
Quality:

Low:
Stream URL 1: Asset not ready for playback
Stream URL 2: Asset not ready for playback
Stream URL 3: This file contains no playable streams

High:
Stream URL 1: Asset not ready for playback
Stream URL 2: Asset not ready for playback
Stream URL 3: This file contains no playable streams

Lossless:
Stream URL 1: Could not determine type of Stream
Stream URL 2: Could not determine type of Stream
Stream URL 3: Could not determine type of Stream

High Res:
Stream URL 1: Could not determine type of Stream
Stream URL 2: Could not determine type of Stream
Stream URL 3: Could not determine type of Stream
```

Nothing works. So I would say this functionality is totally broken unless someone can prove otherwise.

**Comment by BlueManCZ** [comment] 2022-09-19 16:35
There are three "The Endless River" albums from Pink Floyd and two of them stream in 48/24 in my case. Only some music seems to be available in this format.

![obrazek](https://user-images.githubusercontent.com/17854950/191067066-bdb95ef0-cbae-43e0-a685-8609db3753d1.png)
