### ISSUE TITLE
media keys don't wok on Linux Mint

### ISSUE THREAD

**Issue by rijnhard** [jonaski/strawberry#47] opened 2019-01-07 16:16 UTC
play/pause/ff/rw dont respond (it does on clementine).
Using GStreamer -> Alsa -> Meridian Explorer USB DAC

when adjusting the volume on my keyboard I still get the popup which indicates volume changes, but it doesn't change the volume, only when i manually adjust it in strawberry.

with Use gnome keys enabled or disabled.

**Comment by jonaski** [comment] 2019-01-07 18:01
The dbus/gnome backend for shortcuts is unchanged from Clementine, so I don't really see why it should not work. Although I don't use gnome so I have only tested the X11 backend on Linux. (but I rewrote the X11 backend just after christmas).
Are you sure that not another application grabs the same keys, you need to close Clementine and other apps that might make use of the same keys.
I'll probably set up a machine for testing this at some point.
If you start it from the command line does it show any errors?

**Comment by NucleaPeon** [comment] 2019-01-08 01:48
Using gentoo and can confirm as well.
Built on the strawberry 0.4.2-121-gc0e1a9a codebase. (Is there a reason the about window doesn't have selectable text outside the scrollable text area? I'd love to be able to copy-paste the version.)

Shortcuts don't work (FN+left/right/up/down on a thinkpad keyboard)
When I go into settings and shortcuts window, if I try to reset the shortcut to the above key combinations,  nothing will happen. On the main window playlist area, the selector will flicker, so it seems to know something's been pressed, but it doesn't do anything. Shortcuts on Clementine do work. 

I'm using dbus/kde/X11/systemd. Perhaps strawberry is not registering because the plasma widget that comes up when a music player or youtube tab is open (using the plasma chrome addon), doesn't appear.

I do not see any statements when trying to set the shortcuts when running strawberry through my terminal. Let me know if I can provide more information.

**Comment by rijnhard** [comment] 2019-01-08 08:00
Just a note: I'm using cinnamon not gnome, but still.
Willing to test

```
09:58:10.038 DEBUG GnomeGlobalShortcutBackend:96    registered
```

Looks like it's loading fine. strange.

**Comment by jonaski** [comment] 2019-01-08 18:22
If the Gnome settings daemon is installed and works, there is a checkbox for gnome dbus in the settings. Since the dbus backend requires the gnome settings daemon, I don't think it will work on other desktop environments than Gnome and the derivatives. I use XFCE, even if I install the gnome settings, it won't enable it.
The behavior in Clementine was that if the gnome/dbus backend is not found/working, the fallback was to automatically enable the X11 backend, this breaks on a lot of newer distro releases, like Fedora 29. So I made the X11 backend disabled by default (in the newer development builds), and you need to explicitly enable it, or there isn't any global shortcuts. There is a bug report on this here: https://bugzilla.gnome.org/show_bug.cgi?id=765739
They claim X11 is the wrong interface, and it is not supposed to work. I know KDE got it's own interface for grabbing shortcuts, Amarok uses that. But I have not looked into that.
@rijnhard That confirms that you use the gnome/dbus backend. There isn't much debug output on that.
@NucleaPeon Sounds to be like it's completely disabled, there should be some registered/unregistered output when you open / close the settings. Did you enable X11 in the settings?
I will install gnome on a machine to do some testing with the gnome/dbus backend.

**Comment by rijnhard** [comment] 2019-01-08 18:57
I THINK somehow the volume controls are ALWAYS ending up in pulseaudio, which explains why it doesn't work. But this is only a theory and I'm at the end of my knowledge here.

**Comment by NucleaPeon** [comment] 2019-01-08 19:31
@jonaski I applied the "Use X11's shortcut keys" checkbox, but am still seeing the same behaviour though I do see registering in the console now. 
```
11:09:43.908 DEBUG GlobalShortcutBackendSystem:42   Registering
11:09:46.654 DEBUG GlobalShortcutBackendSystem:65   Unregistering
11:09:46.654 INFO  GlobalShortcut:117               Unregister shortcut "Media Next"
11:09:46.654 INFO  GlobalShortcut:117               Unregister shortcut "Media Play"
11:09:46.654 INFO  GlobalShortcut:117               Unregister shortcut "Media Previous"
11:09:46.654 INFO  GlobalShortcut:117               Unregister shortcut "Media Stop"
11:09:46.654 DEBUG GlobalShortcutBackendSystem:42   Registering
```

I closed strawberry and re-opened it, same behaviour. I changed the backend from gstreamer to xine to vlc; I also set the output to auto and to pulseaudio (which I use). Don't know what I expected, but it still didn't make my media keys work nor let me set them.
Not sure if this is meaningful, but I launched `qdbusviewer` session services and looked up strawberry, but clicking the service froze up the program. Using `qdbus org.mpris.MediaPlayer2.strawberry` gave a no reply error.  
Would it be better to try a developer version of the software to test against?

I tested clementine's Configure Shortcuts and lo and behold, I cannot set my shortcuts there either. The media keys work, but setting them doesn't. My issue is primarily that even though strawberry lists the correct default shortcuts that I cannot set, they don't work when I press them.
I can try on some other machines of mine later to see if it's hardware and configuration specific.

**Comment by jonaski** [comment] 2019-01-08 22:31
The gnome d-bus backend was broken with newer versions of gnome-settings-daemon (GSD) because of this change done about a year ago:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/33d47e655606ac88ed7d529c1132e5be6299633b
Fixed now in https://github.com/jonaski/strawberry/commit/411cb27eadc3347a82e861f35aee6f3b5ab9a87f

I can't find anything wrong with the X11 backend, but like I said, it may not work on all Linux desktop.

**Comment by jonaski** [comment] 2019-01-09 21:09
@NucleaPeon I've made the text selectable now, thanks for the tip! 87c2007

**Comment by alekksander** [comment] 2019-01-09 23:36
sadly i have to report, that one of this recent changes broke my media control. system is no longer recognizing if app is, or is not playing.

**Comment by rijnhard** [comment] 2019-01-10 13:05
reading the change Jonas linked, it could be that the changes haven't been backported to the distros you are using.

**Comment by alekksander** [comment] 2019-01-10 19:42
there is no gnome-settings-daemon under kde plasma

**Comment by jonaski** [comment] 2019-01-11 00:07
@alekksander should be fixed in commit c94f907 - I broke mpris because I started a QApplication twice, fixed now by adding a second SingleApplication as a QCoreApplication class.

**Comment by jonaski** [comment] 2019-01-12 12:36
I have installed opensuse with KDE on a machine and I can reproduce problems with shortcuts using the X11 backend.

**Comment by jonaski** [comment] 2019-01-12 12:55
Never mind, I closed and reopened then it works.
However, shortcuts works through MPRIS on KDE so the X11 option should not be checked.
On linux the X11 option should only be checked if shortcuts using MPRIS dont work.
And on Gnome the X11 option should definitely not be used at all as it will break things, shortcuts must be used through GSD (gnome-settings-daemon).

**Closed** 2019-01-12 12:58 UTC
