### ISSUE TITLE
tags of Opus files with the oga extensions arent read

### ISSUE THREAD

**Issue by ArielRosenfeld** [jonaski/strawberry#256] opened 2019-08-27 17:25 UTC
**Describe the bug**
tags of Opus files with the oga extensions arent read and the files are marked as unknown in the tag listing.

the files play with no problem.

**To Reproduce**
add opus file with the extension oga

**Expected behavior**
tags are read

**System Information:**
Operating System: Arch Linux 
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.61.0
Qt Version: 5.13.0
Kernel Version: 5.2.9-arch1-1-ARCH
OS Type: 64-bit
strawberry 0.6.3
gstreamer 1.16.0-2

**Screenshot
![Screenshot_20190827_201856](https://user-images.githubusercontent.com/26487191/63793605-b380e100-c908-11e9-84a2-234313c4426e.jpg)

**Comment by jonaski** [comment] 2019-08-27 17:55
Works here. Tested both Ogg FLAC, Vorbis and Opus with .oga extension.
The relevant part is what version of TagLib you got.
Could you send a file that's not working?

**Comment by ArielRosenfeld** [comment] 2019-08-27 19:45
taglib 1.11.1-3

[Martha Argerich - unknown album - 00 - Barcarolle in F-sharp major, op. 60.zip](https://github.com/jonaski/strawberry/files/3547825/Martha.Argerich.-.unknown.album.-.00.-.Barcarolle.in.F-sharp.major.op.60.zip)

**Comment by jonaski** [comment] 2019-08-27 20:06
Works fine here.
The problem is that Arch is using taglib 1.11.1 and not our provided version which is based on later code from git that have fixes related to identifying audio files.
Could be fixed by the Arch packagers by changing the USE_SYSTEM_TAGLIB option to use our provided version.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/strawberry#n27
Change -DUSE_SYSTEM_TAGLIB=ON to -DUSE_SYSTEM_TAGLIB=OFF
Hopefully there will be a new TagLib release soon which will also solve it.

**Closed by jonaski** 2019-08-27 20:06 UTC

**Comment by AdamantGarth** [comment] 2022-07-13 17:16
I have the same issue - half of my music library is Opus files with the `.ogg` extension, because software I use used to actually support Opus but ignore unknown extensions, `.opus` included. Later they fixed that, so I started to use `.opus` extension. But Strawberry library scanner ignores those older `.ogg` files. If add them from filesystem browser they play fine and the tags get loaded after playback starts.

I also use arch, and the taglib version here is 1.12 now, but looks like that didn't help.

**Comment by jonaski** [comment] 2022-07-16 22:48
Do they work if you rename the files to .opus?

**Comment by AdamantGarth** [comment] 2022-07-17 07:04
They do.
